### ISSUE TITLE
Prep kit/Sequencer model/flow cell requirements for 6mA basecalling

### ISSUE THREAD

**Issue by ywang285** [fiberseq/fibertools-rs#26]
Dear Mitchell,

I am quite new to Pacbio and I would like to detect DNA 6mA (or called DNA m6A? I think they are the same thing, right?) using PacBio and your code. We have access to PacBio Revio. I know that for nanopore sequencing, the latest 6mA basecalling model is trained on specific flow cell (R10) which only works with prep kits using V14 chemistry. I am wondering if there are specific requirements of Pacbio prep kit/Sequencer model (would Revio work?)/flow cell for 6mA basecalling? Thanks!

**Comment by StephanieBohaczuk** [comment]
I can answer this question for you. We have different ML models for different sequencing chemistries but fibertools will automatically pull the sequencing chemistry from the bam header and use the corresponding model, so no need to specify a model manually for most applications. We do have a model for Revio, so that should work just fine. If you're ever merging bam files that might have different sequencing chemistries, just be sure to run them with fibertools first before the merge.

**Comment by ywang285** [comment]
Thank you so much for your reply!

**Comment by mrvollger** [comment]
Thanks for the assist @StephanieBohaczuk and thanks for using fibertools @ywang285!
