### ISSUE TITLE
Questions about ft extract and ft fire commands

### ISSUE THREAD

**Issue by MariosEft97** [fiberseq/fibertools-rs#54]
Hello! Thank you for developing such an amazing tool!

I have a few questions where I would greatly appreciate your insights:

1. When using `ft extract` what does ‘-1’ represent for `ns` and `as` tags?
2. Regarding `ft fire` command, if no model path is defined, are the FIRE calls based on the heuristics only, or is the available trained FIRE model used automatically?
3. How 5mC calls (`--use-5mc` option) are used for FIRE calls?

**Comment by mrvollger** [comment]
Thanks for the questions, these ideally should all be documented, but I am always behind on that. 

1) Positions in columns starting with `ref_` maybe contain `-1` (NA) values if the reference sequence has an insertion or deletion relative to the read sequence at that position. 

2) A pre-trained FIRE model is used if none is specified. Training your own FIRE model is not recommended at this time. The pre-trained model is fairly robust to very different fiber-seq conditions. 

3) 5mC calls are not used in FIRE currently. This was going to be a future option, but it should probably be removed because we have found it not very informative. 

The docs and CLI will be updated in a future release.

**Comment by mrvollger** [comment]
These fixes have been applied in v0.5.0 we have started a documentation website to better answer these questions:
https://fiberseq.github.io/fibertools/fibertools.html
